title: Karen's Website
author: Grumpy Person (Karen)
email: grumpypants18@gmail.ca
description: > # this means to ignore newlines until "baseurl:"
  A website dedicated to somebody who is very grumpy.
theme: minima

# social links
twitter_username: grumpypants18
github_username:  iamgrumpy18

show_excerpts: true # set to false to remove excerpts on the homepage
